[package]
name = "rs-candle"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
candle-core = "0.9.1"
candle-nn = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
