[package]
name = "mnist"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
derive_more = { version = "2.0.1", features = ["full"] }
serde = "1.0.219"
serde_json = "1.0.140"
